package model;

public enum Param {
	ID,	UNIT,QTY, UNITPRICE, TAX, TOTAL, DESCRIPTION, SHOW,
	CLIENT, ADDRESS, PHONE, ORDER, DATE, RUC, CONTACT, EMAIL,
	PROFIT, ACCESORIES,
	EXPAND, METRICS,
	IDENTIFIER,
	DRY_PARANTE, DRY_RIEL, DRY_PLANCHA, DRY_ESQUINERO, DRY_CLAVO, DRY_FULMINATE, DRY_MASILLA,
	CEI_PERIMETRAL, CEI_PRINCIPAL, CEI_SECUNDARIA, CEI_TERCIARIA, CEI_BALDOSA,
	LAM_PIEZA, LAM_ESPUMA, LAM_FILM, LAM_ZOCALO,
	PRO_BUSINESS_PROFIT,
	GROUP_PROFIT, GROUP_ACCSORIES;
	
	
	
}